import Testing
import Foundation
@testable import MLXUI

/// Covers CFM-R5-4: `ErrorCatalog` + `fill(code:values:isV08:)` ported from
/// `catflow-mlx/src/catflow/core/errors_catalog.py`. Every ⚠/⚑ wording must be
/// byte-for-byte the documented text — this suite pins `fill` output against a
/// golden generated by Python's own `fill` (see `scripts/sync-catflow-fixtures.sh`,
/// which re-emits `Fixtures/CatFlow/goldens/errors/fill_golden.json` on every sync).
struct CatFlowErrorCatalogTests {

    private var fixturesDir: URL {
        let filePath = #filePath
        return URL(fileURLWithPath: filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/CatFlow")
    }

    private struct FillCase: Decodable {
        var code: String
        var catalog: String
        var values: [String: String]
        var expected: String
        var closest: Bool?
    }

    // MARK: - fill() matches the Python golden, every code

    @Test func fillMatchesPythonGolden() throws {
        let url = fixturesDir.appendingPathComponent("goldens/errors/fill_golden.json")
        let data = try Data(contentsOf: url)
        let cases = try JSONDecoder().decode([FillCase].self, from: data)
        #expect(cases.count == 161, "expected 61 v07 + 2 E701 + 98 v08 = 161 cases")

        for c in cases {
            let isV08 = c.catalog == "v08"
            let actual = try ErrorCatalog.fill(code: c.code, values: c.values, isV08: isV08)
            #expect(actual == c.expected,
                    "\(c.catalog) \(c.code) fill mismatch — Swift says: \(actual)")
        }
    }

    // MARK: - Both catalogs carry the code sets the Python asserts

    @Test func catalogSizeAndCoverage() {
        // 61/98 is the Python reference's own count; KEY-3 adds one MLXUI-only code
        // on top of each (`R910` — Keychain-backed credentials have no `catflow-mlx`
        // equivalent, see `ErrorCatalog.swift`'s comment beside it), so 62/99 here is
        // "61 ported + 1 Swift-only", not a drift from parity.
        #expect(ErrorCatalog.catalogV07.count == 62)
        #expect(ErrorCatalog.catalogV08.count == 99)
        // E108 exists only at v0.8; E707/E801/R901-R905/F001-F007 are shared.
        #expect(ErrorCatalog.catalogV07["E108"] == nil)
        #expect(ErrorCatalog.catalogV08["E108"] != nil)
        #expect(ErrorCatalog.catalogV07["E701"] != nil)
        #expect(ErrorCatalog.catalogV08["E701"] != nil)
        #expect(ErrorCatalog.catalogV07["R910"] != nil)
        #expect(ErrorCatalog.catalogV08["R910"] != nil)
    }

    // MARK: - E101 / E105 / E108 — the messages the parser surfaces

    @Test func e101V08UnknownVersion() throws {
        let msg = try ErrorCatalog.fill(code: "E101", values: ["version": "0.4"], isV08: true)
        #expect(msg == "This flow says `mlxflow 0.4`. This runtime speaks 0.8 only, and there is no converter. Nothing was run.")
    }

    @Test func e105V08UnparseableRow() throws {
        let msg = try ErrorCatalog.fill(
            code: "E105",
            values: ["n": "7", "fragment": "1. Frobnicate  foo", "detail": "no task name"],
            isV08: true
        )
        #expect(msg == "Row 7 couldn't be read from \"1. Frobnicate  foo…\". A row is: `N. Task  (refs)  model; settings`. The first thing that confused the parser: no task name.")
    }

    @Test func e108PreV08Character() throws {
        let msg = try ErrorCatalog.fill(
            code: "E108",
            values: ["subject": "Row 3", "char": "·", "ascii": ";"],
            isV08: true
        )
        #expect(msg == "Row 3 uses `·`, which mlx-workflow 0.8 replaced with `;`. Run `mlxflow fmt --upgrade` to convert this file. Nothing was run.")
    }

    // MARK: - E701's SPEC-Q50 optional clause

    @Test func e701OptionalClauseIsDroppedWhenNoClosest() throws {
        let msg = try ErrorCatalog.fill(
            code: "E701",
            values: ["key": "temp", "model": "Qwen", "list": "a, b"],
            isV08: true
        )
        #expect(msg == "`temp` isn't a setting Qwen knows. Its settings: a, b.")
    }

    @Test func e701OptionalClauseRendersWhenClosestProvided() throws {
        let msg = try ErrorCatalog.fill(
            code: "E701",
            values: ["key": "temp", "model": "Qwen", "list": "a, b", "closest": "temperature"],
            isV08: true
        )
        #expect(msg == "`temp` isn't a setting Qwen knows. Its settings: a, b. Closest: `temperature`.")
    }

    // MARK: - Missing values fail loudly, like Python's KeyError

    @Test func missingPlaceholderThrows() {
        #expect(throws: ErrorCatalogError.self) {
            try ErrorCatalog.fill(code: "E105", values: ["n": "1"], isV08: true)
        }
    }

    @Test func unknownCodeThrows() {
        #expect(throws: ErrorCatalogError.self) {
            try ErrorCatalog.fill(code: "E999", isV08: true)
        }
    }
}
