import Testing
import Foundation
import SQLite3
@testable import MLXUI

/// CFM-R10-Store — the table pipeline (Read CSV / Query Table / Set Field / Table to Text)
/// and the store door (Store Query / Store Write), pinned against the Python-derived golden
/// (`Fixtures/CatFlow/tools/store_golden.json`, generated by `catflow-mlx/tools/store.py` +
/// `tools/data.py`). Covers the JSON store engine, the SQLite engine, and the identity-column
/// upsert.
struct CatFlowStoreDoorTests {

    private func tempWorkspace() throws -> (workspace: FlowWorkspace, flowID: String) {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("catflow-store-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        return (FlowWorkspace(root: root), "t")
    }

    private func golden() throws -> [String: Any] {
        let url = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .deletingLastPathComponent().appendingPathComponent("Fixtures/CatFlow/tools/store_golden.json")
        return try JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any] ?? [:]
    }

    private func readCSV(_ workspace: FlowWorkspace, _ flowID: String) throws -> Asset {
        let csv = workspace.directory(for: flowID).appendingPathComponent("orders.csv")
        try FileManager.default.createDirectory(at: csv.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "id,status,total\n1,pending,1200\n2,approved,8000\n3,pending,6000\n4,escalated,9500\n".write(to: csv, atomically: true, encoding: .utf8)
        return try TableTool.readCSV(settings: "path=orders.csv", from: csv)
    }

    /// Compare a golden key's table with a Swift table item's `{columns, rows}` — parsed
    /// structurally, so JSON key order never matters.
    private func expectTable(_ asset: Asset, matches key: String) throws {
        let goldenTables = try golden()
        guard let expectedDict = goldenTables[key] as? [String: Any] else {
            Issue.record("missing golden key \(key)")
            return
        }
        let expectedColumns = expectedDict["columns"] as? [String] ?? []
        let expectedRows = expectedDict["rows"] as? [[Any]] ?? []
        let actual = try TableTool.readTable(from: try #require(asset.items.first?.path))
        #expect(actual.columns == expectedColumns, "\(key): columns differ")
        let actualCells = actual.rows.map { row in row.map { TableTool.cellText($0) } }
        let expectedCells = expectedRows.map { row in row.map { TableTool.cellText($0) } }
        #expect(actualCells == expectedCells, "\(key): rows differ from the Python golden")
    }

    // MARK: - Table pipeline (data.py)

    @Test func readCSVMatchesPython() throws {
        let (ws, id) = try tempWorkspace()
        let asset = try readCSV(ws, id)
        try expectTable(asset, matches: "csv_table")
    }

    @Test func queryFilterMatchesPython() throws {
        let (ws, id) = try tempWorkspace()
        let csv = try readCSV(ws, id)
        let item = try #require(csv.items.first)
        let filtered = try TableTool.queryTable(settings: "filter=status=pending", from: item)
        try expectTable(filtered, matches: "query_filter")
    }

    @Test func queryGroupSumMatchesPython() throws {
        let (ws, id) = try tempWorkspace()
        let csv = try readCSV(ws, id)
        let item = try #require(csv.items.first)
        let grouped = try TableTool.queryTable(settings: "group=status; columns=status,total", from: item)
        try expectTable(grouped, matches: "query_group")
    }

    @Test func setFieldMatchesPython() throws {
        let (ws, id) = try tempWorkspace()
        let csv = try readCSV(ws, id)
        let item = try #require(csv.items.first)
        let edited = try TableTool.setField(settings: "status=approved", from: item)
        try expectTable(edited, matches: "set_field")
    }

    @Test func tableToTextMatchesPython() throws {
        let (ws, id) = try tempWorkspace()
        let csv = try readCSV(ws, id)
        let item = try #require(csv.items.first)
        let markdown = try TableTool.tableToText(settings: nil, from: item)
        let expected = try #require(try golden()["to_markdown"] as? String)
        #expect(try #require(markdown.items.first?.value) == expected)
        let csvText = try TableTool.tableToText(settings: "format=csv", from: item)
        let expectedCSV = try #require(try golden()["to_csv"] as? String)
        #expect(try #require(csvText.items.first?.value) == expectedCSV)
    }

    // MARK: - The store door (store.py, JSON engine)

    @Test func storeWriteThenQueryMatchesPython() throws {
        let (ws, id) = try tempWorkspace()
        let csv = try readCSV(ws, id)
        let storeURL = ws.directory(for: id).appendingPathComponent("store.json")
        try #require(try? JSONSerialization.data(withJSONObject: ["orders": []])).write(to: storeURL)

        try StoreTool.storeWrite(inputs: [csv], settings: "path=store.json; table=orders; key=id; mode=insert",
                                 workspace: ws, flowID: id)
        let q = try StoreTool.storeQuery(inputs: [csv], settings: "path=store.json; table=orders; filter=status=pending",
                                         workspace: ws, flowID: id)
        try expectTable(q, matches: "store_query_json")

        // Upsert (no mode → upsert) updates in place.
        try StoreTool.storeWrite(inputs: [csv], settings: "path=store.json; table=orders; key=id",
                                 workspace: ws, flowID: id)
        let q2 = try StoreTool.storeQuery(inputs: [csv], settings: "path=store.json; table=orders; filter=total>5000",
                                          workspace: ws, flowID: id)
        try expectTable(q2, matches: "store_query_upsert")
    }

    @Test func storeWriteRefusesUnknownTableOrMissingKey() throws {
        let (ws, id) = try tempWorkspace()
        let csv = try readCSV(ws, id)
        let storeURL = ws.directory(for: id).appendingPathComponent("store.json")
        try #require(try? JSONSerialization.data(withJSONObject: ["orders": []])).write(to: storeURL)
        #expect(throws: (any Error).self) {
            try StoreTool.storeWrite(inputs: [csv], settings: "path=store.json; table=missing; key=id; mode=insert",
                                     workspace: ws, flowID: id)
        }
        #expect(throws: (any Error).self) {
            try StoreTool.storeWrite(inputs: [csv], settings: "path=store.json; table=orders; mode=upsert",
                                     workspace: ws, flowID: id)
        }
    }

    // MARK: - The store door (SQLite engine)

    @Test func storeWriteThenQuerySQLite() throws {
        let (ws, id) = try tempWorkspace()
        let csv = try readCSV(ws, id)
        let dbURL = ws.directory(for: id).appendingPathComponent("orders.db")

        // Create an existing `orders` table in the store file.
        var db: OpaquePointer?
        sqlite3_open(dbURL.path, &db)
        sqlite3_exec(db, "CREATE TABLE orders (id INTEGER PRIMARY KEY, status TEXT, total INTEGER)", nil, nil, nil)
        sqlite3_close(db)

        try StoreTool.storeWrite(inputs: [csv], settings: "path=orders.db; table=orders; key=id; mode=insert",
                                 workspace: ws, flowID: id)
        let q = try StoreTool.storeQuery(inputs: [csv], settings: "path=orders.db; table=orders; filter=status=pending",
                                         workspace: ws, flowID: id)
        let path = try #require(q.items.first?.path)
        let (columns, rows) = try TableTool.readTable(from: path)
        #expect(columns == ["id", "status", "total"])
        #expect(rows.count == 2)
        #expect(rows.allSatisfy { ($0[1] as? String) == "pending" })

        // Upsert updates the existing rows by key.
        try StoreTool.storeWrite(inputs: [csv], settings: "path=orders.db; table=orders; key=id",
                                 workspace: ws, flowID: id)
        let q2 = try StoreTool.storeQuery(inputs: [csv], settings: "path=orders.db; table=orders",
                                          workspace: ws, flowID: id)
        let path2 = try #require(q2.items.first?.path)
        let (_, rows2) = try TableTool.readTable(from: path2)
        #expect(rows2.count == 4)
    }

    // MARK: - The 56 flow's shape runs

    @Test func orderTriageQueueIsRunnableNow() throws {
        // canRun already allowed store rows; CFM-R12-FIX-1 removed the metadata gate.
        let doc = try GalleryLoader.loadDocument(flowID: "56-OrderTriageQueue")
        #expect(FlowRunner.canRun(doc) == .runnable)
    }
}
